[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl = "BYQsrTrL2PUdDqGBAVqvG5aQwi8B3pLnM4aimWyF1qQe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/danny/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
