[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl = "4KEugcVcMHtkBqQrgX2Fu8u3CSBu3BTrpuFigWoArEJS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/danny/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
